### ISSUE TITLE
Add Interactive plot in website doc

### ISSUE THREAD

**Issue by ajouary** [orger-lab/megabouts#6]
It would be nice to make plots interactive. Current attempt using plotly in the notebook Loading_Data fail to display in the website (error message: "Data type cannot be displayed: application/vnd.plotly.v1+json")

**Comment by ajouary** [comment]
Solved using myst-nb instead of nbsphinx, see for examples:

https://myst-nb.readthedocs.io/en/v0.11.0/examples/interactive.html#ipywidgets

**Comment by AlexandreLaborde** [comment]
That version of the myst-nb docs is for an ancient version.
Link to the latest version https://myst-nb.readthedocs.io/en/latest/render/interactive.html
